local o = vim.opt

o.autoindent = true
o.autoread = true
o.backup = false
o.cursorline = true
o.expandtab = true
o.mouse = 'a'
o.hlsearch = true
o.ignorecase = true
o.linebreak = true
o.laststatus = 2
o.scrolloff = 10
o.mousehide = true
o.number = true
o.numberwidth = 1
o.relativenumber = true
o.ruler = true
o.shiftwidth = 2
o.showmatch = true
o.showcmd = true
o.smartindent = true
o.smarttab = true
o.tabstop = 2
o.title = true
o.updatetime = 300
o.wildmenu = true
o.wrap = true
